# Generated by Django 4.2.1 on 2023-06-10 03:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=16, unique=True)),
                ('fec_nac', models.DateField()),
                ('email', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('peso', models.FloatField(blank=True, default=0)),
                ('altura', models.FloatField(blank=True, default=0)),
                ('imc', models.FloatField(blank=True, default=0)),
                ('id_alim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.alimentacion')),
            ],
            options={
                'verbose_name': 'Usuario de MisRutinas',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
        ),
    ]
