# Generated by Django 4.2.1 on 2023-06-10 21:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_logro'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioLogro',
            fields=[
                ('id_userlogro', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('completed_at', models.DateField(blank=True, default=datetime.date.today)),
                ('fk_logro', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.logro')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Logro de Usuario',
                'verbose_name_plural': 'UsuariosLogros',
                'db_table': 'UsuarioLogro',
            },
        ),
    ]
