# Generated by Django 4.2.1 on 2023-06-13 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suscripcion', '0003_pago'),
        ('usuarios', '0004_usuariologro'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_sub',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='suscripcion.suscripcion'),
        ),
    ]
