# Generated by Django 4.2.1 on 2023-06-10 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suscripcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('nro_comp', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('fk_suscripcion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='suscripcion.suscripcion')),
            ],
            options={
                'verbose_name': 'Factura de MisRutinas',
                'verbose_name_plural': 'Facturas',
                'db_table': 'Factura',
            },
        ),
    ]
