# Generated by Django 4.2.1 on 2023-06-10 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suscripcion', '0002_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('subtotal', models.FloatField(default=0)),
                ('detalle', models.TextField(blank=True, default='', max_length=100)),
                ('fk_id_factura', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='suscripcion.factura')),
            ],
            options={
                'verbose_name': 'Pago suscripciones',
                'verbose_name_plural': 'Pagos',
                'db_table': 'Pago',
            },
        ),
    ]
