# Generated by Django 4.2.1 on 2023-06-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id_set', models.AutoField(primary_key=True, serialize=False)),
                ('serie', models.IntegerField()),
                ('repeticion', models.IntegerField(blank=True, default=0)),
                ('duracion', models.TimeField(blank=True, default='00:00:00')),
                ('descanso', models.TimeField()),
            ],
            options={
                'verbose_name': 'Set de Rutinas',
                'verbose_name_plural': 'Sets',
                'db_table': 'Set',
            },
        ),
    ]
