# Generated by Django 4.2.1 on 2023-06-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaCuerpo',
            fields=[
                ('id_zonacuerpo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Zona de Cuerpo Trabajada',
                'verbose_name_plural': 'Zonas del Cuerpo',
                'db_table': 'ZonaCuerpo',
            },
        ),
    ]
