# Generated by Django 4.2.1 on 2023-06-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0002_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id_rutina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('serie', models.IntegerField()),
                ('repeticion', models.IntegerField()),
                ('duracion', models.TimeField()),
                ('descanso', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Rutina de ejercicios',
                'verbose_name_plural': 'Rutinas',
                'db_table': 'Rutina',
            },
        ),
    ]
