# Generated by Django 4.2.1 on 2023-06-12 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0005_rutina'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetRutina',
            fields=[
                ('id_setrut', models.AutoField(primary_key=True, serialize=False)),
                ('fk_rut', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rutinas.rutina')),
                ('fk_set', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rutinas.set')),
            ],
            options={
                'verbose_name': 'Set de ejercicios para rutina',
                'verbose_name_plural': 'Setsrutinas',
                'db_table': 'SetRutina',
            },
        ),
    ]
