# Generated by Django 4.2.1 on 2023-06-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0006_setrutina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='id_ejerc',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
