# Generated by Django 4.2.1 on 2023-06-13 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_id_sub'),
        ('rutinas', '0007_alter_ejercicio_id_ejerc'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='fk_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
